### ISSUE TITLE
Gabriel's suggestions and feedback July 17th 2024

### ISSUE THREAD

**Issue by gnrgoldstein** [lubianat/wikiora#13]
Feedback in July 17th  2024

- [x] Website is crashing when dealing with long lists.
- [x]  It would be good to accept files, either lists or tables (less necessary but still could be good).
- [x]  When changing analysis types, don't change the current gene list (atm is suggesting new random genes each time you change).
- [x] Running a new search with the same gene dataset from the results page would make it more user friendly.

**Comment by lubianat** [comment]
Implemented POST support for long lists. I'll upload to the server later in the day.

**Comment by lubianat** [comment]
all implemented in https://github.com/lubianat/wikiora/commit/ddf9531500f083172c4b1bebe874562d523999c9
