### ISSUE TITLE
Feedback/Sugestões do João

### ISSUE THREAD

**Issue by jvfe** [lubianat/wikiora#3]
Cara ta mt legal! Seguem algumas coisas que te falei no telegram, mas com certeza cabem muito melhor aqui. Em ordem do que eu acho mais importante:

- [x] Eu sentiria falta de poder submeter o genelist como um arquivo, é muito mais conveniente que ter que abrir um arquivo com uma lista de genes, copiar, colocar as virgulas e tal. Acho que tu não teria problema de implementar a lógica. Seria essencialmente um formulário que o usuário submete um arquivo txt, onde cada linha é um gene distinto. Pra deixar ainda mais fácil colocaria até um arquivo pequeno de exemplo no site.

- [x]  Um usuário provavelmente gostaria de poder baixar a tabela como um CSV ou algo assim. Não sei o quão fácil isso é pois não tive tempo de olhar o código do teu app, mas acho q posso dar alguns caminhos de como fazer isso.

- [x] Se você já tá fazendo um teste hipergeométrico, você provavelmente já tem o número total de genes em um termo/tipo celular, então eu colocaria uma coluna de Gene Ratio na tabela (tamanho do input/n de componentes do termo).

- [x] Associado a feature acima, seria legal de ver um dotplot como esse: https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#dot-plot ou algo parecido. A documentação do clusterprofiler pode te dar algumas ideias de como visualizar esses resultados.

- [x] "Click on a description to modify the displayed Wikipedia page." eu modificaria isso para "Click on a description to display its Wikipedia page". Juro pra ti que modify a princípio me passou a ideia que seria editar a página da wikipédia.

- [ ] Acho que talvez o botão de randomize deveria randomizar a seleção do "analysis type" e "organism" também, na minha opinião deixaria mais divertido, pois você sempre estaria explorando um aspecto diferente, resultando em maior explorabilidade.

De forma geral, pensa que um usuário típico (i.e. não programador) vai inserir a lista de genes dele lá, pegar a tabela pra editar num excel e provavelmente usar a visualização pronta que você já fornece. Então se tu quiseres abarcar essa galera, tem que pensar em como melhor disponibilizar sua tabela/seu gráfico e deixar todo o processo o mais simples possível. Um usuário programador vai só pegar o GMT que tu gerou e usar independentemente, inclusive gostei muito que tu deu essa opção.

Falei meio que de forma livre, então fique a vontade pra editar a mensagem pra deixar goals mais concretos.

**Comment by lubianat** [comment]
Excelente feedback! No geral, acho tudo tranquilo de implementar. Vou fazendo aos poucos.

**Comment by lubianat** [comment]
Implementei no último commit: 

- https://github.com/lubianat/wikiora/commit/370bd9884a1324307550d9d50d5125fe087aeffb

Curti a ideia do Randomize múltiplo, mas acho que prefiro do jeito que tá (pelo menos pros testes por agora)
